### ISSUE TITLE
TODO Tasks

### ISSUE THREAD

**Issue by engmtcdrm** [engmtcdrm/minno#1]
- [x] Make app executable path dynamic, if in $PATH, set to app name, otherwise full pathname/how this is running, i.e. build...
- [x] Refactor colors of prompts
- [x] ~~Refactor `ResolveCredName` func to be attached to `Credential` struct~~
    - [x] ~~Refactor code to start using this~~
- [ ] Add `SetName` or something func for `Credential` struct
     - [ ] Refactor code to start using this
- [x] Figure out how to CI/CD releases

**Comment by engmtcdrm** [comment]
I've forgotten what `SetName` stuff is so I'm just closing this. Clearly irrelevant at this point.
